<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sql_metamodel" nsURI="sql_metamodel" nsPrefix="sql_metamodel">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listSchemas" upperBound="-1"
        eType="#//Schema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listAllTables" upperBound="-1"
        eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listTables" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listPrimaryKeys" upperBound="-1"
        eType="#//PrimaryKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listForeignKeys" upperBound="-1"
        eType="#//ForeignKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listColumns" upperBound="-1"
        eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listRelations" upperBound="-1"
        eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNotNull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutoIncremetable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryKey" eSuperTypes="#//Column"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKey" eType="#//PrimaryKey"/>
  </eClassifiers>
</ecore:EPackage>
