<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ucdiagram" nsURI="http://ucdiagram" nsPrefix="ucdiagram">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listDiagrams" upperBound="-1"
        eType="#//uc_diagram" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uc_diagram">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listActors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listBoxes" upperBound="-1"
        eType="#//LimitBox" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listComRels" upperBound="-1"
        eType="#//comRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listIncRels" upperBound="-1"
        eType="#//includeRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listExtRels" upperBound="-1"
        eType="#//extendsRelationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/ucdiagrama/svg/actor.svg"/>
      <details key="label.layout" value="center"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UseCase">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/ucdiagrama/svg/useCase.svg"/>
      <details key="label.layout" value="center"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useCaseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objective" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listPreconditions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listPostconditions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listFlowEvents" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listExceptions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LimitBox">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.layout" value="center"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useCases" upperBound="-1"
        eType="#//UseCase" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="comRelationship">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//UseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="includeRelationship">
    <eAnnotations source="gmf.link">
      <details key="label" value="labelName"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;include>"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//UseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="extendsRelationship">
    <eAnnotations source="gmf.link">
      <details key="label" value="labelName"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;extends>"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//UseCase"/>
  </eClassifiers>
</ecore:EPackage>
